# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LEOexit
email: BetterAngels@riseup.net
description: > # this means to ignore newlines until "baseurl:"
    LEOexit is an initiative that helps people leave the law enforcement and corrections industries
    and build a new life. It is civil society&rsquo;s response to the lack of oversight and undemocratic
    practices of law enforcement agencies and the prison industrial complex.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
